### ISSUE TITLE
Editor just shows up blank

### ISSUE THREAD

**Issue by sampathsris** [benweet/stackedit-chrome-extension#5]
I am using Google Chrome Version 68.0.3440.106 (Official Build) (64-bit), and the extension version 1.0.3.

When I try to launch the editor in stackoverflow.com or github.com, it just shows a blank screen:

![image](https://user-images.githubusercontent.com/3192154/43871866-5728397a-9b9c-11e8-9e38-3619cc3c0b88.png)

This blank screen goes away at the slightest of the mouse move.

Following errors (among others) are shown in the console:

```
Uncaught (in promise) TypeError: Cannot read property 'postMessage' of undefined
    at content_script.js:6812
```
![image](https://user-images.githubusercontent.com/3192154/43871962-cd1e2414-9b9c-11e8-9c13-e54a65af7ec9.png)

Admittedly, this seems to be originating from a dependency, but still I would be grateful if you could take a look. Please let me know if you need further information. Thank you.

**Comment by sampathsris** [comment]
There is also this error, that seems to originate from https://stackedit.io/static/js/app.1fbf8cf9ea784dee956f.js.

```
app.1fbf8cf….js:1 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at Object.<anonymous> (https://stackedit.io/static/js/app.1fbf8cf9ea784dee956f.js:1:130746)
    at n (https://stackedit.io/static/js/manifest.3dfa1ce307d25b7947ca.js:1:101)
    at window.webpackJsonp (https://stackedit.io/static/js/manifest.3dfa1ce307d25b7947ca.js:1:418)
    at https://stackedit.io/static/js/app.1fbf8cf9ea784dee956f.js:1:1
```

Do let me know if you want me to open separate issues for any of these. Thanks.
